---
- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: reload_prometheus
  uri:
    url: http://localhost:9090/-/reload
    method: POST
    status_code: 200
